In [1]:
import pandas as pd

In [3]:
# Load the data
file_path = 'ori_dataset/goldstandard.txt'
data = pd.read_csv(file_path, sep='\t')  # Assuming tab-separated values

# Convert to CSV
output_path = 'dataset/goldstandard.csv'
data.to_csv(output_path, index=False)

print(f'Data saved to {output_path}')

display(data)

Data saved to dataset/goldstandard.csv

,#CUE_COLUMN,FRAGMENT_COLUMN,INSTANCE_COLUMN,EXTREME_COLUMN,LEXICALIZATION_COLUMN,OPPOSING_SENTIMENT_COLUMN,TABOO_COLUMN,ANTONYM_COLUMN,UNUSUAL_COLUMN,LABEL_COLUMN
0,I hate you.,I ... you greatly.,I don't admire you greatly.,_,_,_,_,_,_,ABUSE
1,I hate you.,I ... you.,I struggle to respect you.,_,_,_,_,_,UNUSUAL,ABUSE
2,I hate you.,I always need ... with you.,I always need a drink before dealing with you.,EXTREME,_,_,TABOO,_,UNUSUAL,ABUSE
3,I hate you.,I am not ... you.,I am not fond of you.,_,_,_,_,_,_,ABUSE
4,I hate you.,I can think of better ... than ... in your ...,I can think of better things to do than be in ...,_,_,_,_,_,_,ABUSE
...,...,...,...,...,...,...,...,...,...,...
1792,You grump.,You have,You have a personality that is never positive.,EXTREME,_,_,_,_,_,ABUSE
1793,You grump.,You love,You love turning a positive into a negative.,_,_,OPPOSING_SENTIMENT,_,_,UNUSUAL,ABUSE
1794,You grump.,You make ... look happy.,You make a mortician look happy.,EXTREME,_,OPPOSING_SENTIMENT,_,_,UNUSUAL,ABUSE
1795,You grump.,You wouldn't,You wouldn't know a compliment if it was said ...,EXTREME,_,_,_,ANTONYM,UNUSUAL,ABUSE
1796,You grump.,Your ability to ignore ... is astonishing.,Your ability to ignore the pleasures of life i...,EXTREME,_,OPPOSING_SENTIMENT,_,_,UNUSUAL,ABUSE

In [8]:
# Load the goldstandard data
goldstandard = pd.read_csv('dataset/goldstandard.csv')

# Base path for original fold files and path for saving updated fold files
orig_folds_path = 'ori_dataset/Folds/'
updated_folds_path = 'dataset/Folds/'
fold_files = ['instances.fold1.txt', 'instances.fold2.txt', 'instances.fold3.txt', 'instances.fold4.txt', 'instances.fold5.txt']

# Ensure the directory exists
import os
if not os.path.exists(updated_folds_path):
    os.makedirs(updated_folds_path)

# Process each fold file
for file in fold_files:
    # Load the fold data, skipping rows that start with the hash symbol
    fold_data = pd.read_csv(orig_folds_path + file, sep='\t', header=None, names=['CUE_PHRASE', 'INSTANCE'], comment='#')

    # Merge to match instances and add labels
    merged_data = fold_data.merge(goldstandard[['INSTANCE_COLUMN', 'LABEL_COLUMN']], left_on='INSTANCE', right_on='INSTANCE_COLUMN', how='left')

    # Drop the extra 'INSTANCE_COLUMN'
    merged_data.drop('INSTANCE_COLUMN', axis=1, inplace=True)

    # Save the updated fold data with labels as CSV
    updated_filename = file.replace('instances.', '').replace('.txt', '.csv')
    merged_data.to_csv(updated_folds_path + updated_filename, index=False)
    print(f'Updated data saved to {updated_folds_path}{updated_filename}')
    display(merged_data)

Updated data saved to dataset/Folds/fold1.csv

,CUE_PHRASE,INSTANCE,LABEL_COLUMN
0,You are anorexic.,You should eat more.,OTHER
1,You are anorexic.,"If you get any thinner, you'll be transparent.",ABUSE
2,NO_CUE,"If you get any feedback, you'll be confused.",OTHER
3,NO_CUE,"If you get any money, you'll be sure to spend ...",OTHER
4,You are anorexic.,You would look more attractive with a bit more...,ABUSE
...,...,...,...
355,NO_CUE,There isn't anything that you don't have.,OTHER
356,NO_CUE,There isn't anything that you won't do for a l...,OTHER
357,You fail at everything.,You are not a productive member of society.,ABUSE
358,You fail at everything.,You don't seem to have found what you are good...,OTHER
359,You fail at everything.,Your life is far from being perfect.,ABUSE

Updated data saved to dataset/Folds/fold2.csv

,CUE_PHRASE,INSTANCE,LABEL_COLUMN
0,You are boring.,You are dulling my senses.,ABUSE
1,You are boring.,You inspire me to fall asleep.,ABUSE
2,NO_CUE,You inspire me to be more organised.,OTHER
3,NO_CUE,You inspire me to recycle.,OTHER
4,You are boring.,There is nothing of interest in your life.,ABUSE
...,...,...,...
352,NO_CUE,Your commitment to your values is admirable.,OTHER
353,NO_CUE,Your honesty is admirable.,OTHER
354,NO_CUE,Your kindness is admirable.,OTHER
355,NO_CUE,Your patience is admirable.,OTHER
356,NO_CUE,Your willingness to endure pain in the pursuit...,OTHER

Updated data saved to dataset/Folds/fold3.csv

,CUE_PHRASE,INSTANCE,LABEL_COLUMN
0,You are a hooligan.,You should do anger management training.,OTHER
1,NO_CUE,You should look into developing your critical ...,OTHER
2,You are a hooligan.,You have no self-control.,OTHER
3,NO_CUE,You have no fat on you.,OTHER
4,NO_CUE,You have no idea how your words can affect peo...,OTHER
...,...,...,...
359,NO_CUE,I can only hope that you learn from your mista...,OTHER
360,You are irresponsible.,Your lack of self-awareness is astonishing.,ABUSE
361,NO_CUE,Your adaptability is astonishing.,OTHER
362,NO_CUE,Your debut novel is astonishing.,OTHER
363,NO_CUE,Your hair is astonishing.,OTHER

Updated data saved to dataset/Folds/fold4.csv

,CUE_PHRASE,INSTANCE,LABEL_COLUMN
0,You are mad.,You'll do well within the confines of padded w...,ABUSE
1,NO_CUE,You'll do well within the confines of your spe...,OTHER
2,You are mad.,I think we need to give you anti-psychotics fr...,ABUSE
3,NO_CUE,I think we need to give you easier chores from...,OTHER
4,You are mad.,You have lost the plot.,ABUSE
...,...,...,...
352,NO_CUE,I always thought you were talented in maths an...,OTHER
353,NO_CUE,I always thought you were talented in other ar...,OTHER
354,NO_CUE,I always thought you were talented in visual a...,OTHER
355,You are ignorant.,You never pay attention to those around you.,OTHER
356,NO_CUE,I think you are spreading a feeling of tension...,OTHER

Updated data saved to dataset/Folds/fold5.csv

,CUE_PHRASE,INSTANCE,LABEL_COLUMN
0,You are arrogant.,You are overwhelmingly confident.,OTHER
1,You are arrogant.,You could learn to be more modest.,OTHER
2,NO_CUE,You couldn't listen to other people's opinions...,OTHER
3,You are arrogant.,You'd tell the Prince of Wales how to be polite.,ABUSE
4,NO_CUE,You'd tell him how to be more proficient.,OTHER
...,...,...,...
354,NO_CUE,Success must be your middle name.,OTHER
355,You are quarrelsome.,You like to voice your own opinions loudly.,ABUSE
356,You are quarrelsome.,You make it hard to agree.,OTHER
357,NO_CUE,You make sure you always get the first choice ...,OTHER
358,You are quarrelsome.,You love to look for an issue.,ABUSE